### ISSUE TITLE
OPTION-N shortcut key doesn't Run

### ISSUE THREAD

**Issue by russch** [Acconut/brackets-nodejs#17]
Brackets Sprint 38 on Mavericks, Node JS Bindings 1.1.3

Repro: 
1. Open an app.js file. Hit OPTION-1 and OPTION-SHIFT-1: Note that built-in Brackets shortcut keys using OPTION are collapsing/expanding source. 
2. Hit OPTION-N

Result: A tilde (~) character appears in source
Expect: app.js to be run by Brackets

**Comment by kindalu** [comment]
I face the same issue today...

This page explains how OS X treat the Alt_key.
https://en.wikipedia.org/wiki/Alt_key
---
If I hold Alt-Key and type from A-Z, I will get this
å∫ç∂´ƒ©˙ˆ∆˚¬µ˜øπœ®ß†¨√∑≈¥Ω
