### ISSUE TITLE
Parse the package.json "scripts":[] for the Run as ... menu

### ISSUE THREAD

**Issue by Jackbennett** [Acconut/brackets-nodejs#32]
Is it possible to just parse the projects Package.json scripts section for the menu actions to go in brackets?

There's an open ticket for npm debug I assume at some point someone will ask for custom tasks so is it possible to just skip to using the defined commands in the package?

For instance my project looks like;

``` json
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1",
    "start-dev": "nodemon server",
    "start": "node server.js"
  },
```

So I could get the "start dev" listed in the brackets menu.

**Comment by sagiegurari** [comment]
Is this project still alive?
I would love to see this one implemented as I do all my work via npm scripts.
But seems this one is open for over a year.

**Comment by Acconut** [comment]
I am not using Brackets as my main editor anymore but still kind of maintain this project. This mostly includes fixing bugs but not bigger features due to time issues. I am sorry. :(

**Comment by sagiegurari** [comment]
I can understand that.
Anyway, thanks for the reply.
