### ISSUE TITLE
Specify project 'main' file

### ISSUE THREAD

**Issue by dtruel** [Acconut/brackets-nodejs#41]
Hello,

First, amazing plugin.  Thank you so much.  Second, I'm working on a Node app with several server side files.  I have one "main.js" entry file that always starts it.  Is there an easy way to make a new setting so that it can always execute the "main.js" file instead of the one I'm currently working on?

Thank you

**Comment by dtruel** [comment]
Or actually, I just saw the rerun button, so that pretty much takes care of it.  I can just hit that and it will rerun main.js.  Is there a keyboard shortcut for that?

**Comment by Acconut** [comment]
Yes, the rerun function behaves as you said. It terminates the current process and starts it again. You should also have a look at the `Run as npm start` option in the dropdown which will execute `npm start` so you can specify the command inside your `package.json`.
Currently there is no shortcut for this functionality so you have to click the button.
