### ISSUE TITLE
Terminal does not update if process console does not use new line.

### ISSUE THREAD

**Issue by PatrickMurphy** [Acconut/brackets-nodejs#43]
## Expected Behavior:
   Each time process writes to the console it should update the terminal with that new message regardless of a new line. (If you run node in other programs like `cmd.exe` this is how it works)
 
## Actual Behavior:
  If I do not print a new line character the terminal is not updated until the next newline is seen or the program exits.
 
## Steps to reproduce:
  Use `process.stdout.write()` instead of `console.log()` to print data to the console.  Until your program writes a newline char `\n` it does not show on the terminal.

### Example:

      var intervalExecCount = 0;
      var intervalID = setInterval(function(){
	  ++intervalExecCount;
	  if(intervalExecCount<5){
              process.stdout.write('.'); // won't print this until process ends
	  }else{
	      clearInterval(intervalID);
	  }
        }, 1000);

**Comment by Acconut** [comment]
Sorry, for not respond but I was not at home. Anyway, the reason for this behaviour is that the Server-sent-events (SSE) protocol which is used for communicating with the node process is using `\n` as the end of a message.

I haven't used Brackets for a while but I'll give this a shot.

**Comment by Acconut** [comment]
1.4.1 has been publish which should fix this problem. Please restart the entire editor to take advantage of this new functionality. And, of course, thanks for reporting this bug. :)

**Comment by PatrickMurphy** [comment]
Thanks so much Acconut! I will be using this right away!

**Comment by Acconut** [comment]
No problem :) Feel free to come back if it does not work as intended.
