### ISSUE TITLE
Permissions problem for location of node/npm

### ISSUE THREAD

**Issue by petercz1** [Acconut/brackets-nodejs#44]
Hi,

node.js>run and node.js>execute won't run. For the first one I get 'Program exited' when running a simple node server, but this server does run on the command line. For the second if I use 'node -v' I get the same, and yet the command line gives v0.12.7.

If I run node.js> run as npm test I get '/bin/sh: 1: npm: not found'

'which node/npm' gives me a directory of '/home/pc/.linuxbrew/bin' for both. If I set both 'node.js>configuration> paths to node/npm'  to this path I get:
'/bin/sh: 1: /home/pc/.linuxbrew/bin: Permission denied'

I am owner:group pc:pc on this directory and paths to it, and ps aux shows pc is running brackets:

pc       12785  0.5  0.4 579096 55464 ?        Sl   12:56   0:03 /opt/brackets/Brackets --lang=en-US --log-severity=disable --remote-debugging-port=9234 --no-sandbox
pc       12790  0.0  0.1 306208 16000 ?        S    12:56   0:00 /opt/brackets/Brackets --lang=en-US --log-severity=disable --remote-debugging-port=9234 --no-sandbox
pc       12791  0.0  0.2 313168 33776 ?        S    12:56   0:00 /opt/brackets/Brackets --type=zygote --no-sandbox --lang=en-US --log-severity=disable
pc       12809  0.1  0.7 1015740 87856 ?       Sl   12:56   0:01 /opt/brackets/Brackets-node /opt/brackets/node-core
pc       12812  1.7  1.5 1618724 183848 ?      Sl   12:56   0:09 /opt/brackets/Brackets --type=renderer --no-sandbox 

Node was installed via linuxbrew, I'm running Ubuntu 15.04 mate 64bit.

I'm clearly doing something daft here - any ideas what??

Best wishes,

PC

**Comment by petercz1** [comment]
Aha! progress - where the node.js>configuration says 'path to node binary' it expects the 'node' command on the end, not just the path. So instead of:

/home/pc/.linuxbrew/bin

I now have:

/home/pc/.linuxbrew/bin/node

This will run. (I'm killing it with 'node.js> run as npm stop' - is this the right way to kill?)

However, I still see no output for node.js > execute command> node -v.

Also node.js > execute command> npm ls gives '/bin/sh: 1: npm: not found' even though the path is now set as '/home/pc/.linuxbrew/bin/npm' as per 'which npm => /home/pc/.linuxbrew/bin/npm'

PC

**Comment by Acconut** [comment]
I just publish version 1.4.1 of this extension which introduced some new internal transportation mode. In order to make debugging for me easier, would you please be so kind and update the extension and test again?

**Comment by petercz1** [comment]
Hi Marius,

Some quick testing:

'node.js > run' is ok,

'node.js >  execute command > node -v' gives:

'Program exited with status code of 1.'\

'node.js >  execute command > npm ls' gives:

'Program exited with status code of 127./bin/sh: 1: npm: not found'

in settings I have path to node/npm libraries set to

/home/pc/.linuxbrew/bin/node
/home/pc/.linuxbrew/bin/npm

'which node/npm' gives me:

/home/pc/.linuxbrew/bin/node
/home/pc/.linuxbrew/bin/npm

Hope this helps!

PC

**Comment by Acconut** [comment]
I tried to replicate this issue by installing node through Linuxbrew but I had no trouble. Some more time is needed for me to figure this out.

**Comment by petercz1** [comment]
Cool.

It works just great for firing off node from within brackets, a BIG help.

Am I stopping node correctly by using 'node.js > run as npm stop'?

PC

**Comment by Acconut** [comment]
>  Am I stopping node correctly by using 'node.js > run as npm stop'?
No, the `run as npm stop` button while execute the `npm stop` command which is used to run the stop script specified in the package.json. This is usually used for cleaning up deamons, but not stopping the actual node process. In order to do that, you can use the button in the top right corner of the terminal.
